name: Debug Workflow Events

on:
  release:
    types: [created, published, released, prereleased, edited, deleted]
  repository_dispatch:
    types: [docker-build]
  workflow_dispatch:

jobs:
  debug-all-events:
    runs-on: ubuntu-latest
    steps:
      - name: Debug All Events
        run: |
          echo "=== EVENT DEBUG ==="
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "=== RELEASE EVENT ==="
            echo "Release ID: ${{ github.event.release.id }}"
            echo "Release Tag: ${{ github.event.release.tag_name }}"
            echo "Release Name: ${{ github.event.release.name }}"
            echo "Release Draft: ${{ github.event.release.draft }}"
            echo "Release Prerelease: ${{ github.event.release.prerelease }}"
            echo "Release Published At: ${{ github.event.release.published_at }}"
            echo "Release Target Commitish: ${{ github.event.release.target_commitish }}"
            echo "Release Author: ${{ github.event.release.author.login }}"
          fi
          
          if [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
            echo "=== REPOSITORY DISPATCH EVENT ==="
            echo "Event Type: ${{ github.event.action }}"
            echo "Client Payload: ${{ toJson(github.event.client_payload) }}"
          fi